import os

PRIMARY_MODEL_NAME = "qwen3:8b"
PRIMARY_MODEL_TEMPERATURE = float(os.getenv("PRIMARY_MODEL_TEMPERATURE", 0.3))
PRIMARY_MODEL_TYPE = os.getenv("PRIMARY_MODEL_TYPE", "local")
PRIMARY_CHARACTER = "THE_SILENT"

LANGSMITH_API_KEY = "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"
LANGSMITH_PROJECT = "sts-agent"
LANGSMITH_ENDPOINT = "https://api.smith.langchain.com"
LANGSMITH_ENABLED = True